# 建立 nginx pod 測試掛載及寫入資料至 NFS 磁碟
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: nginx-web
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc1
